### ISSUE TITLE
Geoerver not getting UP while deploying as StatefulSet in Kubernetes

### ISSUE THREAD

**Issue by saingithub** [geosolutions-it/docker-geoserver#111]
I was trying to deploy geoserver as a StatefulSet in Kubernetes. When we mount the data directory geoserver is not getting up.

I was getting the error in the logs as waiting for the geoserver to be up and running.

I was able to deploy without mounting the directory and there is no persistance for the data in that case.

Could you please guide as in deploying as a StatefulSet

**Comment by saingithub** [comment]
I had given /var/geoserver/datadir as the mountpath

**Comment by randomorder** [comment]
Hi @saingithub 

From what you say it doesn't look like a problem with the docker image itself, maybe with the statefulset or persistent volume and claim definitions in kubernetes... 

Check the permissions on the directory to make sure it writable by the user that is running tomcat (and geoserver) in the container

There is also  an HELM Chart readily available for the deployment of a geoserver cluster or to inspect and see how we have defined volumes and mounts for the data directory [here](https://github.com/geosolutions-it/charts/tree/main/geoserver/latest)

**Comment by saingithub** [comment]
When we give /var/geoserver/ or /var/geoserver/datadir as the mount path. The geoserver is not getting Up.

Do you have a Statefulset yaml file

**Comment by randomorder** [comment]
it's templated in the Helm chart [here](https://github.com/geosolutions-it/charts/blob/main/geoserver/latest/templates/statefulset.yaml). Hope it helps

**Comment by saingithub** [comment]
We have deployed using the helm chart you have shared. The pod is Up and running , but there is no persistance for the data .

I created a test workspace and restarted the pod. The workspace got deleted when the pod got up.

All the volume claims are still there.

**Comment by randomorder** [comment]
Sorry for the late reply. In case you are still facing this problem please create an issue in the [Chart implementation repository](https://github.com/geosolutions-it/charts/issues). This repo is for the docker image itself. Thank you
